#Define the type of quarto project (new from .RMD)
project:
  type: website #Make sure to `touch .nojekyll` in terminal to supress github jekyll auto 
  output-dir: docs #Need to specify (something other than _site for github pages)
  render: 
    - "*qmd"
    - "*.QMD"
    - "*.rmd"
    - "*.RMD"
    - "*.Rmd"
    - "!flexdashboard*"
    - "!nyc_airbnb_shiny_dashboard_leaflet.RMD"
    - "!pubh_7462/lecture_week_14_shiny_app"
    
#Defines the main part(s) of the website: navbar, buttons, icons, links, etc.
website:
  title: "Quinton Neville"
  navbar:
    type: default
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: qn_resume.html
      - text: "Advanced Data Science in R"
        menu:
          - text: "PUBH 7462 Advanced `R` Syllabus"
            href: pubh_7462/syllabus.QMD
          - text: "`Students' Final Project Website Showcase!`"
            href: pubh_7462/final_projects.QMD
          - text: "NYC Airbnb `shiny` `flexdashboard` Example"
            href: https://nevilleq.shinyapps.io/nyc_airbnb_shiny_dashboard_leaflet/
          - text: "NYC Airbnb `flexdashboard` Example"
            href: pubh_7462/lecture_week_7/flexdashboard_activity_solution.html
          - text: "Lecture: Data Visualization (`ggplot2`, `gt`)"
            href: pubh_7462/lecture_week_4/lecture_week_4.Rmd
          - text: "Lecture: Interactive Plots, Tables & Dashboards"
            href: pubh_7462/lecture_week_7/lecture_week_7.Rmd
          - text: "Lecture: Websites with `R` & Github"
            href: pubh_7462/lecture_week_9/lecture_week_9.Rmd
          - text: "Lecture: Advanced Spatial Mapping"
            href: pubh_7462/lecture_week_11/lecture_week_11.Rmd
          - text: "Lecture: Git Collaboration & Intro to `shiny`"
            href: pubh_7462/lecture_week_12/lecture_week_12.Rmd
          - text: "Lecture: `shiny` Apps & Dashboards"
            href: pubh_7462/lecture_week_14/lecture_week_14.Rmd
      - text: "Biostatistics"
        menu:
          - text: "Bayesian Robust RCM"
            href: https://nevilleq.github.io/bayesRCM/
          - text: "RCM for Task-based fMRI"
            href: https://docs.google.com/presentation/d/1andU17E2c4d0fsUdMi3aWm1-B1P7Fm-QqzXcEXmNA9Q/edit?usp=sharing
          - text: "ML-Boosting SNP Classification"
            href: old_work/ml_theory.Rmd
          - text: "TCGA Bumphunting for Differential Methylation"
            href: old_work/stat_gen.Rmd
      - text: "Data Science for the Public Good"
        menu:
          - text: "DSPG Overview"
            href: old_work/dspg_overview.Rmd
          - text: "Geospatial Composite Index"
            href: old_work/fairfax.Rmd
          - text: "Innovation & ML Text Classification"
            href: old_work/business_innovation.Rmd
          - text: "Dog Bites in NYC"
            href: old_work/dog_bites.Rmd
    right:
      - icon: github
        href: http://github.com/nevilleq/
      - icon: linkedin
        href: https://www.linkedin.com/in/quinton-neville/
      - icon: envelope
        href: mailto:<nevil066@umn.edu>
  page-footer: 
      left: "Copyright 2022 | QN" 
      right: 
      - icon: github
        href: http://github.com/nevilleq/
      - icon: linkedin
        href: https://www.linkedin.com/in/quinton-neville/
      - icon: envelope
        href: mailto:<nevil066@umn.edu>
        
#Define output format, .css, and other basic style options
format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    code-block-bg: "#ECECEC"
    page-layout: full

#Execution (warning, message, echo, eval, etc.)
# execute:
#   cache: true


