---
title: "NYC Airbnb Leaflet Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
library(shiny)
library(leaflet)

#Working directory for .RMD
# knitr::opts_knit$set(echo = TRUE,
#                      root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = FALSE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```

```{r data_read, include = FALSE}
#Read in the nyc airbnb data set
nyc.df <- read_csv("./data/nyc_airbnb.csv", show_col_types = FALSE) %>%
  mutate(rating  = review_scores_location / 2) %>%
  filter(price <= 1000) %>%
  rename(borough = neighbourhood_group) %>%
  dplyr::select(borough, neighbourhood, rating, price,
                room_type, lat, long, contains("review")) %>%
  drop_na(rating) %>%
  mutate(
    text_label = str_c(neighbourhood, 
                       "<br>Price: "  ,  scales::dollar(price),
                       "<br>Rating: ",    rating, "/5",
                       "<br>Reviews/Month: ", reviews_per_month)
  )
```


```{r input_choices, echo = FALSE}
#Pull all the different boro names (5)
boro_choices <- nyc.df %>%
  distinct(borough) %>%
  pull()

#Price range (vector length 2 w/ min max)
price_range <- nyc.df %>% 
  pull(price) %>%
  range()

#Pull all the different room choices
room_choices <- nyc.df %>%
  distinct(room_type) %>%
  pull()
```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r ui, echo = FALSE}
#Define a slider input for price range (using above)
sliderInput(
  inputId = "price",
  label   = h2("Price Range"),
  min     = price_range[1],
  max     = price_range[2],
  value   = c(100, 500), #starting range
  ticks   = FALSE
)

#Define a radio button for different room choices
radioButtons(
  inputId  = "room",
  label    = h2("Accommodation Type"),
  choices  = room_choices,
  selected = room_choices[2] #Entire home/apt
)

#Define a drop down menu for borough
selectInput(
  inputId  = "borough",
  label    = h2("Select Borough"),
  choices  = boro_choices,
  selected = boro_choices[5] #Manhattan
)
```

```{r input_filter, echo = FALSE}
#Filter the data based on the inputs above
#Use reactive expression
dataFilter <- reactive({
#Filter the original data and return as reactive output below
nyc.df %>%
  filter(
  price > input[["price"]][1],
  price < input[["price"]][2],
  room_type %in% input[["room"]],
  borough %in% input[["borough"]], 
  )
})
```

### **Average Rating**   

```{r avg_rating, echo = FALSE}
renderGauge({
  #Compute average rating 
  avg_rating <- dataFilter() %>%
                pull(rating) %>%
                mean(., na.rm = TRUE)
  #Render the gauge
  gauge(
    round(avg_rating, 1),
    min = 0,
    max = 5,
    #sectors = gaugeSectors(
    #           success = c(4.5, 5),
    #           warning = c(3, 4.5),
    #           danger  = c(0, 3)
    #          )
  )
})
```

### **Price-Rating Correlation**   

```{r correlation, echo = FALSE}
renderGauge({
  #Compute average rating 
  nyc.df <- dataFilter()
  
  #Render the gauge
  gauge(
    round(cor(nyc.df$price, nyc.df$rating), 1),
    min = -1,
    max = 1,
    sectors = gaugeSectors(
               danger  = c(0.5, 1),
               warning = c(0, 0.5),
               success = c(-1, 0) 
              )
  )
})
```

Column {data-width=600}
-----------------------------------------------------------------------  

### Map of Airbnb's between `r reactive({ str_c("$", input[["price"]][1], " - $", input[["price"]][2]) })` in `r reactive({ input[["borough"]]} )` for `r reactive({ input[["room"]]})`


```{r leaflet, echo = FALSE}
#Render our leaflet like normal (see Week 11 lecture for leaflet)
renderLeaflet({
  
  #Store reactive dataFilter as data frame for further use
  nyc.df <- dataFilter()
  
  #Turn the filtered nyc data into an sf object
  nyc_sf.df  <- sf::st_as_sf(nyc.df, coords = c("lat", "long"))
  
  #Create pallete based on filtered data
  my_pallete <- colorNumeric(viridis::viridis_pal(option = "C")(4),
                             domain  = c(input[["price"]][1],
                                         input[["price"]][2]))
  
  #Create the leaflet
  leaflet(data = nyc_sf.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(price),
    label   = ~map(text_label, HTML), #map over labels, make html
    opacity = 0.4, #alpha
    weight  = 1, #outline strength
    radius  = 2 #size of circle
  ) %>%
  addLegend(
    title     = "Airbnb Price",
    position  = "bottomright",
    pal       = my_pallete,
    values    = ~sort(price, decreasing = TRUE),
    #labFormat = labelFormat(transform = function(x) {str_c("$ ", x)})
    #labels   = shop_types 
  )
})
```


### Distribution of `r reactive({ input[["borough"]]} )`'s Airbnb Price by Neighborhood  

```{r price_box}
renderPlotly({
  #Store to grab unique neighborhoos for pallete
  nyc.df  <- dataFilter()
  n_hoods <- nyc.df$neighbourhood %>% unique() %>% length() 
  
  #Render plotly
  nyc.df %>%
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price, median, .desc = FALSE)
  ) %>%
  plot_ly(
    y      = ~price,
    color  = ~neighbourhood,
    type   = "box",
    colors = viridis::viridis_pal(option = "C")(n_hoods) 
  ) %>%
  layout(
    title  = "Distribution of Airbnb Price by Neighbourhood",
    xaxis  = list(title = "Price")
  )
})
```


### Number of Listings in `r reactive({ input[["borough"]]} )` by Neighborhood  

```{r n_listings}
renderPlotly({
  #Call reactive filtered data
  nyc.df  <- dataFilter()
  n_hoods <- nyc.df$neighbourhood %>% unique() %>% length()
  
  #Render plot
nyc.df %>%
  group_by(neighbourhood) %>%
  summarise(
    N = n()
  ) %>%
  mutate(
    neighbourhood = fct_reorder(neighbourhood, N, .desc = FALSE)
  ) %>%
  plot_ly(
    y = ~neighbourhood,
    x = ~N,
    color  = ~neighbourhood,
    type   = "bar",
    colors = viridis::viridis_pal(option = "C")(n_hoods) 
  ) %>%
  layout(
    title  = "Number of Listings by Neighbourhood",
    xaxis  = list(title = "Neighbourhood"),
    yaxis  = list(title = "Number of Listings")
  )
})
```